[G7T5-90] Display All Learning Journeys View
is212g7t5/spm pull request #27
Opened 2022-09-29 15:42 UTC by theianchia

# Description

Fixes [G7T5-90](https://is212g7t5.atlassian.net/jira/software/c/projects/G7T5/boards/4?modal=detail&selectedIssue=G7T5-90)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Refactor
- [ ] Migration

# How Has This Been Tested?
- [ ] I have added the corresponding testcases into the [testcase document](https://docs.google.com/spreadsheets/d/1QOyUN_kFN0fddLkjAQz2DK3jou3cWdN9CJsNbl3v0Kg/edit#gid=0)

Please indicate the testcase ID you have added or are using

- [ ] G7T5-1-1
- [ ] G7T5-1-2

# Checklist:

- [ ] I have added the appropriate labels to my PR
- [ ] My code follows the style guidelines of this project
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-09-30 01:46 UTC, quinncheong requested changes

2022-09-30 01:46 UTC, quinncheong commented on app/src/App.jsx
>  import Courses from "./routes/courses";
Might want to use absolute imports src/...

2022-09-30 01:46 UTC, quinncheong commented on app/src/components/course/index.jsx
> +    <div className='flex flex-row container w-9/12 max-w-7xl mt-10 p-10 mx-auto w-full bg-white rounded-lg shadow-lg shadow-blue-200'>
Does it need flex-row because default flex = flex-row

2022-09-30 01:46 UTC, quinncheong commented on app/src/components/learningJourney/LearningJourneyTile.jsx
> +    <div className="max-w-sm bg-white rounded-lg border border-gray-100 hover:shadow-lg hover:shadow-orange-200 mt-10 mx-5">
Possible to refactor this into smaller components but in the same file? Something like jobTile

2022-09-30 01:46 UTC, quinncheong commented on app/src/components/learningJourney/index.jsx
> +  const LearningJourneyData = [
Pull mockdata out of functions, rename to mockXXXXX. I have create a mockdata file also under utils. Can place it inside if u want.

2022-09-30 06:46 UTC, quinncheong approved these changes
Merge once ur ready if u think it's ok to leave the mock data as is.

2022-10-01 03:41 UTC, theianchia commented on app/src/components/learningJourney/LearningJourneyTile.jsx
> +      <img className="mb-3 w-24 h-24 rounded-full shadow-lg" src="https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=fo
currently a placeholder till we find something we want to replace with

2022-10-01 04:28 UTC, merged